export const valuation_data = [
  {
    type: "Project Valuation (App)",
    fixedPercent: 0.2,
    phases: [
      { phase: "UI", percent: 0.2 },
      { phase: "App Design + Integration", percent: 0.22 },
      { phase: "App Integration", percent: 0.09 },
      { phase: "Dashboard Design", percent: 0.09 },
      { phase: "Dashboard Integration", percent: 0.04 },
      { phase: "Backend", percent: 0.31 },
      { phase: "App Deployment", percent: 0.025 },
      { phase: "Web Deployment", percent: 0.025 },
    ],
  },
  {
    type: "Project Valuation (Web)",
    fixedPercent: 0.2,
    phases: [
      { phase: "UI", percent: 0.2 },
      { phase: "Website Design", percent: 0.22 },
      { phase: "Website Integration", percent: 0.09 },
      { phase: "Dashboard Design", percent: 0.09 },
      { phase: "Dashboard Integration", percent: 0.04 },
      { phase: "Backend", percent: 0.31 },
      { phase: "Deployment", percent: 0.05 },
    ],
  },
  {
    type: "Project Valuation (App+Web)",
    fixedPercent: 0.2,
    phases: [
      { phase: "UI", percent: 0.2 },
      { phase: "App Design", percent: 0.15 },
      { phase: "App Integration", percent: 0.07 },
      { phase: "Website Design", percent: 0.11 },
      { phase: "Website Integration", percent: 0.05 },
      { phase: "Dashboard Design", percent: 0.08 },
      { phase: "Dashboard Integration", percent: 0.04 },
      { phase: "Backend", percent: 0.25 },
      { phase: "App Deployment", percent: 0.025 },
      { phase: "Web Deployment", percent: 0.025 },
    ],
  },
  {
    type: "Project Valuation (App+Web) + AI",
    fixedPercent: 0.2,
    phases: [
      { phase: "UI", percent: 0.2 },
      { phase: "App Design", percent: 0.14 },
      { phase: "App Integration", percent: 0.06 },
      { phase: "Website Design", percent: 0.09 },
      { phase: "Website Integration", percent: 0.04 },

      { phase: "Dashboard Design", percent: 0.07 },
      { phase: "Dashboard Integration", percent: 0.03 },
      { phase: "Backend", percent: 0.2 },
      { phase: "AI", percent: 0.12 },
      { phase: "App Deployment", percent: 0.025 },
      { phase: "Web Deployment", percent: 0.025 },
    ],
  },
  {
    type: "Project Valuation (App) With AI",
    fixedPercent: 0.2,
    phases: [
      { phase: "UI", percent: 0.17 },
      { phase: "App Design", percent: 0.18 },
      { phase: "App Integration", percent: 0.07 },
      { phase: "Dashboard Design", percent: 0.08 },
      { phase: "Dashboard Integration", percent: 0.04 },
      { phase: "Backend", percent: 0.25 },
      { phase: "AI", percent: 0.16 },
      { phase: "Web Deployment", percent: 0.025 },
      { phase: "App Deployment", percent: 0.025 },
    ],
  },
  {
    type: "Project Valuation (Web) With AI",
    fixedPercent: 0.2,
    phases: [
      { phase: "UI", percent: 0.17 },
      { phase: "Website Design", percent: 0.18 },
      { phase: "Website Integration", percent: 0.07 },
      { phase: "Dashboard Design", percent: 0.08 },
      { phase: "Dashboard Integration", percent: 0.04 },
      { phase: "Backend", percent: 0.25 },
      { phase: "AI", percent: 0.16 },
      { phase: "Web Deployment", percent: 0.05 },
    ],
  },
];
